language: c
sudo: required
dist: trusty
compiler:
    - gcc
before_install:
    - ./.install_dependencies.sh
install:
    - mkdir build
    - cd build
    - cmake ..
    - make dtc
    - make

script:
    - make check
    - make system_test
