language: c
sudo: required
dist: trusty

compiler:
    - gcc

before_install:
    - ./.install_dependencies.sh

install:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - make dtc
    - make
    - make system_test
    - sudo apt-get install -y python3-pip
    - sudo python3 -m pip install -r ../tests/system_test/requirements.txt

script:
<<<<<<< HEAD
    - make check
    - sudo python3 ../tests/system_test/system_test.py --debug -v -r 'PKCS11 TWO MASTERS' .
