language: c
sudo: required
dist: trusty
compiler:
    - gcc
before_install:
    - ./.install_dependencies.sh
install:
    - mkdir build
    - cd build
    - cmake ..
    - make dtc
    - make
    - make system_test

script:
    - make check
    - python3 ../tests/system_test/system_test.py ./ -v --debug -r "PKCS11 TWO NODES" -d ./
