language: python
python:
    - "3.4"

sudo: required
dist: trusty

compiler:
    - gcc

before_install:
    - ./.install_dependencies.sh

install:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - make dtc
    - make
    - make system_test
    - pip install -r ../tests/system_test/requirements.txt

script:
    - make check
