language: c
sudo: required
dist: trusty
compiler:
    - gcc
before_install:
    - ./.install_dependencies.sh
install:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - make dtc
    - make
    - make system_test
    - sudo python3 -m pip install -r ../tests/system_test/requirements.txt
before_script:
    - echo $PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python3/dist-packages:/usr/local/lib/python3.4/dist-packages
    - echo $PYTHONPATH
script:
    - make check
