language: python
python:
    - "3.5"

sudo: required
dist: trusty

compiler:
    - gcc

before_install:
    - ./.install_dependencies.sh
    - pip install --upgrade pip
    - pip install -r tests/system_test/requirements.txt

install:
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING=ON ..
    - make dtc
    - make
    - make system_test

script:
    - make check